# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/derth/projects/fpga/wsolated/wsolated/wsolated.srcs/sources_1/ip/AudioClock/AudioClock.xci
# IP: The module: 'AudioClock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/derth/projects/fpga/wsolated/wsolated/wsolated.gen/sources_1/ip/AudioClock/AudioClock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AudioClock'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/derth/projects/fpga/wsolated/wsolated/wsolated.gen/sources_1/ip/AudioClock/AudioClock.xdc
# XDC: The top module name and the constraint reference have the same name: 'AudioClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/derth/projects/fpga/wsolated/wsolated/wsolated.gen/sources_1/ip/AudioClock/AudioClock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AudioClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/derth/projects/fpga/wsolated/wsolated/wsolated.srcs/sources_1/ip/AudioClock/AudioClock.xci
# IP: The module: 'AudioClock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/derth/projects/fpga/wsolated/wsolated/wsolated.gen/sources_1/ip/AudioClock/AudioClock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AudioClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/derth/projects/fpga/wsolated/wsolated/wsolated.gen/sources_1/ip/AudioClock/AudioClock.xdc
# XDC: The top module name and the constraint reference have the same name: 'AudioClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/derth/projects/fpga/wsolated/wsolated/wsolated.gen/sources_1/ip/AudioClock/AudioClock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AudioClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
