# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/Arty-A7-35-Master.xdc

# IP: ip/PCMROM/PCMROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCMROM || ORIG_REF_NAME==PCMROM} -quiet] -quiet
