# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/derth/projects/fpga/wassolldas/wsolated/wsolated.srcs/sources_1/ip/WSOLARAM/WSOLARAM.xci
# IP: The module: 'WSOLARAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/derth/projects/fpga/wassolldas/wsolated/wsolated.gen/sources_1/ip/WSOLARAM/WSOLARAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'WSOLARAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/derth/projects/fpga/wassolldas/wsolated/wsolated.srcs/sources_1/ip/WSOLARAM/WSOLARAM.xci
# IP: The module: 'WSOLARAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/derth/projects/fpga/wassolldas/wsolated/wsolated.gen/sources_1/ip/WSOLARAM/WSOLARAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'WSOLARAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
